### PR TITLE
fix: RESET clears inflight fetches

### LINKED ISSUE #1072: RESET should prevent resolve/rejection of inflight promises
In resolve/reject function, check for existence in inflight requests *or* using abortcontroller.

Note: this means non-throttle requests will need some form of bookkeeping

### PR DESCRIPTION
**Pull request by ntucker**
Fixes #1072 .

### Motivation

[reset](https://resthooks.io/docs/api/useResetter) clears inflight promises, not just state already established.

This is critical when using RESET for auth logout as the subsequent promises will likely reject with auth errors.

#### Visible Behavior

- unmounting CacheProvider with inflight requests will not attempt to dispatch after unmount causing react error
  - promises are neither resolved nor rejected
- upon reset, all inflight requests will not dispatch receives
  - promises still reject so external listeners know (abort signals do this as well)
- useResource(), useRetrive() will re-issue needed fetches upon reset so they never end up loading infinitely
  - this only triggers *after* commit of reset action so users have a chance to unmount those components if they are no longer relevant (like doing a url redirect from an unauthorized page)

#### Implementation details
- Reset action includes date. This is stored in state as 'lastReset'. This is used to trigger refetches in useRetrieve()
  - NetworkManager now relies on getState() - using it to find the lastReset time. This determines whether to dispatch actions after a fetch completes
  - Since reset is a 'singleton action', tracking the last time allows us to simply compare current fetch times with last reset to know whether to process their dispatches.
- No special test code for fetch date - instead remove it from snapshots so tests don't break on every run

### CODE REVIEW

**Comment by ntucker** [comment]
Adding tests now

File: packages/core/src/state/NetworkManager.ts [hunk 1]
```diff
@@ -29,6 +34,7 @@ export default class NetworkManager implements Manager {
   declare readonly dataExpiryLength: number;
   declare readonly errorExpiryLength: number;
   protected declare middleware: Middleware;
+  private lastClear = new Date(-1);
```
Comment (ljharb) [inline packages/core/src/state/NetworkManager.ts:37]: seems like maybe doing `new Date(NaN)` would be a clearer choice?

**Review by ljharb — APPROVED** [review]

File: packages/core/src/state/NetworkManager.ts (hunk 1 above)
Comment (ntucker) [reply packages/core/src/state/NetworkManager.ts:37]: new Date(NaN) < new Date(0) === false

Whatever is on left hand side I want to always be less than right hand side.

Comment (ljharb) [reply packages/core/src/state/NetworkManager.ts:37]: in that case, just `-Infinity`? ie, not a date object at all

Comment (ntucker) [reply packages/core/src/state/NetworkManager.ts:37]: Oh nice, didn't realize that had such a property 👍
