### PR TITLE
fix: Resource.url properties are enumerable when provided

### LINKED ISSUE #1727: Resource with 'url' property returns '__url' when using spread syntax
**React version** 7.0.2

**Package manager version** yarn 1.22.17
**Node version** 17.14.0

**Rest Hooks version** 6.1.7

**Describe the bug**
Using the spread syntax `...` on a resource object returns `__url` instead of the `url` that I expected. 

**Minimum reproducable example or test case**
Here's a minimal example.  

`test.tsx`
 ```typescript class 
Test extends Resource {
  readonly id: string;
  readonly url: string;
          
  pk() {
    return this.id;
  }
          
  static urlRoot = `http://localhost:7000/test`;  // returns {id: '1', url: 'www.test-url.com}
}
```

`App.tsx`
```typescript
function App() {
    const test = useResource(Test.detail(), {});
    console.log({...test});
    return (
        <AsyncBoundary>
            <div className="App"/>
        </AsyncBoundary>
    );
}

interface Props {
    fallback?: React.ReactElement;
    children: React.ReactNode;
}

function AsyncBoundary({children, fallback = <p>'loading'</p>}: Props) {
    return (
        <Suspense fallback={fallback}>
            <NetworkErrorBoundary>{children}</NetworkErrorBoundary>
        </Suspense>
    );
}
```

The console output
```typescript
{id: '1', __url: 'www.test-url.com'}
```

**Expected behavior**
Output I was expecting
```typescript
{id: '1', url: 'www.test-url.com'}
```

### PR DESCRIPTION
**Pull request by ntucker**
Fixes #1727 .

### Motivation

Resources should return the same object initialized with fromJS() when they are enumerated through spread. This matches normally expected behavior.

### Solution

We can still provide a non-enumerable url getter in the prototype by making the setter define url in the instance with `Object.defineProperty`. Previous attempts to do this failed due to not using the special method. We also test hasOwnProperty() behavior

### CODE REVIEW

File: packages/experimental/src/rest/BaseResource.ts [hunk 1]
```diff
@@ -236,21 +234,24 @@ export default abstract class BaseResource extends EntityRecord {
...
-    // typescript thinks constructor is just a function
-    const Static = this.constructor as typeof BaseResource;
-    return Static.url(this);
-  },
-  set(url: string) {
-    this.__url = url;
-  },
-});
+  static {
+    Object.defineProperty(this.prototype, 'url', {
```
Comment (ljharb) [inline packages/experimental/src/rest/BaseResource.ts:239]: I’m confused why this isn’t defined as a normal prototype getter/setter?

File: packages/rest/src/SimpleResource.ts [hunk 2]
```diff
@@ -377,21 +375,24 @@ export default abstract class SimpleResource extends EntityRecord {
...
-    const Static = this.constructor as typeof SimpleResource;
-    return Static.url(this);
-  },
-  set(url: string) {
-    this.__url = url;
-  },
-});
+  static {
+    Object.defineProperty(this.prototype, 'url', {
+      get(): string {
```
Comment (ljharb) [inline packages/rest/src/SimpleResource.ts:381]: Same question here

**Review by ljharb — APPROVED** [review]

File: packages/experimental/src/rest/BaseResource.ts (hunk 1 above)
Comment (ntucker) [reply packages/experimental/src/rest/BaseResource.ts:239]: Typescript distinguishes between getters but I don't want the types to be that way

Comment (ntucker) [reply packages/experimental/src/rest/BaseResource.ts:239]: Otherwise a user cannot declare a non getter type, which is exactly what is enabled by the setter definition.

Comment (ljharb) [reply packages/experimental/src/rest/BaseResource.ts:239]: It seems very unfortunate to write worse actual code just to make TS types happy.

Comment (ntucker) [reply packages/experimental/src/rest/BaseResource.ts:239]: Are there any downsides other than just looking uglier?
