### PR TITLE
fix: Do not run reducer on non-optimistic fetches

### LINKED ISSUE #300: Various warnings in React 16.13.1
**React version** 16.13.1

**Concurrent mode** no

**Describe the bug**
React throws warnings when useResource is used anywhere:

```
Warning: Cannot update a component (`CacheProvider`) while rendering a different component (`PartnerRewards`). To locate the bad setState() call inside `PartnerRewards`, follow the stack trace as described in https://fb.me/setstate-in-render
```

### PR DESCRIPTION
**Pull request by ntucker**
Fixes #300  .

### Motivation

Even though the state does not update, React will warn about the reducer running from render (triggered from useRetrieve()). Although React should short-circuit and not actually re-render, it doesn't harm for us to short-circuit even earlier - after all it will run less code!

### Solution

Intercept all fetch dispatches in the NetworkManager that cannot cause state updates. (No optimistic response)

### CODE REVIEW

File: packages/rest-hooks/src/react-integration/hooks/useError.ts [hunk 1]
```diff
@@ -20,9 +20,7 @@ export default function useError<
     if (!meta.error) {
       // this means we probably deleted the entity found in this result
       const err: any = new Error(
-        `Resource not found in cache ${
-          params ? fetchShape.getFetchKey(params) : ''
```
Comment (ntucker) [inline packages/rest-hooks/src/react-integration/hooks/useError.ts]: this was actually not needed - as params is already discriminated above.
