### PR TITLE
enhance: Keep referential equality in list views

### LINKED ISSUE #249: listShape lacks reference equality across rerenders
**React version** 16.12.0

**Concurrent mode** no

**Describe the bug**
The return value of useResource(MyResource.listShape(), {}) is referentially different on every rerender, with some of the returned MyResource instances also being referentially different. This makes it difficult to optimize things.

**To Reproduce**
1. Make a resource
2. `const myResourceList = useResource(MyResource.listShape(), {});`
3. `useEffect(() => console.log(myResourceList), [myResourceList]);`
4. Trigger a rerender on that component (setting state, etc)
5. Observe `myResourceList` being logged 

**Expected behavior**
`myResourceList` should be referentially stable across renders if it is being pulled from cache.

**Additional context**
Any console errors? What does the networking inspector show?

### PR DESCRIPTION
**Pull request by ntucker**
Fixes #249 .

### Motivation

- Performance
- Hooks world expects this - like useEffect, etc

### Solution

- Track all entities captured in denormalize
- Serialize them
- Use that serialization as memo check for results

### Open questions

How does this affect performance overall? Could this be degrading non-list cases?

### CODE REVIEW

File: packages/normalizr/src/index.js [hunk 1]
```diff
@@ -155,41 +155,44 @@ const getUnvisit = entities => {
   const cache = {};
   const getEntity = getEntities(entities);
 
-  return function unvisit(input, schema) {
```
Comment (ntucker) [inline packages/normalizr/src/index.js]: this whole block until denormalizeAndTracked  is actually just returning `[previousReturn, cache]`

Formatting changed each line due to the tabbing over.

File: packages/rest-hooks/src/resource/SimpleRecord.ts [hunk 2]
```diff
@@ -8,6 +8,13 @@ interface SimpleResourceMembers<T extends typeof SimpleRecord> {
 
 /** Immutable record that keeps track of which members are defined vs defaults. */
 export default abstract class SimpleRecord {
+  // a 'unique' identifier to make referential equality comparisons easy
+  declare readonly _unq: string;
```
Comment (ntucker) [inline packages/rest-hooks/src/resource/SimpleRecord.ts]: this is sort of a hack for react not wanting variable sync comparisons. we'll be serializing this later

File: packages/rest-hooks/src/state/selectors/useDenormalized.ts [hunk 3]
```diff
@@ -63,13 +63,31 @@ export default function useDenormalized<
...
       schema,
       entities,
     );
-    return [denormalized, entitiesFound] as any;
+
+    // this enables us to keep referential equality based on entities contained within
+    const entitiesList = Object.values(cache)
+      .map(Object.values)
+      .reduce((a: any[], b: any[]) => a.concat(b), [])
+      .join(',');
```
Comment (ntucker) [inline packages/rest-hooks/src/state/selectors/useDenormalized.ts]: serializing this list so react doesn't complain. this is somewhat dangerous as people not using `Entity` will have troubles.

**Comment by kmartinezmedia** [comment]
Looks good to me. Would like to know if we can answer, `How does this affect performance overall? Could this be degrading non-list cases?` or if this is negligible.

**Comment by ntucker** [comment]
I could create some synthetic benchmarks to run. For non-list cases since the entity list will be incredibly small, while it will have some non-zero impact, it probably won't be large
